CFLAGS=-Wall -g

all: ex1 ex3
clean:
	rm -f ex1
	rm -f ex3
	rm -f ex4
	rm -f ex5
	rm -f ex6
	rm -f ex7
	rm -f ex10
	rm -f ex11
	rm -f ex11_external1
	rm -f ex11_external2
	rm -f ex12
	rm -f ex12_external
	rm -f ex13
	rm -f ex14
	rm -f ex16
	rm -f ex16_external
